<?php

/**
 * @file
 * Provides a GDMI reports entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\tb_gdmi_reports\Entity\GdmiReport;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function tb_gdmi_reports_theme() {
  return [
    'gdmi_report' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for GDMI report templates.
 *
 * Default template: gdmi-report.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the GDMI report information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_gdmi_report(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function tb_gdmi_reports_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish tb GDMI report.
      $storage = \Drupal::entityTypeManager()->getStorage('gdmi_report');
      $gdmi_report_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($gdmi_report_ids) as $gdmi_report) {
        $gdmi_report->set('status', FALSE);
        $gdmi_report->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize tb GDMI report.
      $storage = \Drupal::entityTypeManager()->getStorage('gdmi_report');
      $gdmi_report_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($gdmi_report_ids) as $gdmi_report) {
        $gdmi_report->setOwnerId(0);
        $gdmi_report->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function tb_gdmi_reports_user_predelete(UserInterface $account) {
  // Delete tb GDMI report.
  $storage = \Drupal::entityTypeManager()->getStorage('gdmi_report');
  $gdmi_report_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $gdmi_reports = $storage->loadMultiple($gdmi_report_ids);
  $storage->delete($gdmi_reports);
}
