<?php

/**
 * @file
 * Primary module hooks for Thunderbird Webform module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function tb_webform_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//  dpm($form_id);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function tb_webform_form_node_degree_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'tb_webform/tb_webform';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function tb_webform_form_webform_submission_path_degrees_add_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // If degree_type is not master
  // remove hybrid option in delivery method
  $values = $form_state->getValues();
  if (isset($values['degree_type']) && ($values['degree_type'] != 'master')) {
    unset($form['elements']['page_delivery_method']['delivery_method']['#options']['hybrid']);
  }

  // If degree_type is master
  // delivery_method is in_person
  // remove worldwide option in location
  if (isset($values['degree_type']) && ($values['degree_type'] == 'master')) {
    if (isset($values['delivery_method']) && ($values['delivery_method'] == 'in_person')) {
      unset($form['elements']['page_location']['location']['#options']['worldwide']);
    }
  }

  // If degree_type is master
  // delivery_method is hybrid
  // remove phx and dc option in location
  if (isset($values['degree_type']) && ($values['degree_type'] == 'master')) {
    if (isset($values['delivery_method']) && ($values['delivery_method'] == 'hybrid')) {
      unset($form['elements']['page_location']['location']['#options']['phx']);
      unset($form['elements']['page_location']['location']['#options']['dc']);
    }
  }
}

/**
 * Implements hook_entity_type_build().
 */
function tb_webform_entity_type_build(&$entity_types) {
  if (isset($entity_types['webform_submission'])) {
    $entity_types['webform_submission']->setFormClass('add', 'Drupal\tb_webform\TbWebformSubmissionForm');
  }
}
