/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function (Drupal) {
    Drupal.theme.message = function (_ref, _ref2) {
      var text = _ref.text;
      var type = _ref2.type,
        id = _ref2.id;

      const newTypes = {
        status : 'success',
        error: 'danger',
        warning: 'warning',
      }

      const icons = {
        status : '<span title="Alert" class="fa fa-icon fa-check-circle"></span>',
        error: '<span title="Alert" class="fa fa-icon fa-exclamation-triangle"></span>',
        warning: '<span title="Alert" class="fa fa-icon fa-bell"></span>',
      }

      var messageWrapper = document.createElement('div');
      messageWrapper.setAttribute('class', `alert alert-${newTypes[type]}`);
      messageWrapper.setAttribute('role', 'alert');
      messageWrapper.setAttribute('aria-labelledby', "".concat(id, "-title"));
      messageWrapper.setAttribute('data-drupal-message-id', id);
      messageWrapper.setAttribute('data-drupal-message-type', newTypes[type]);
      messageWrapper.innerHTML = `
        <div class="alert-icon">${icons[type]}</div>
        <div class="alert-content">${text}</div>
        <div class="alert-close">
          <button type="button" class="btn btn-circle btn-circle-alt-black close" data-bs-dismiss="alert" aria-label="Close">
            <i class="fas fa-times" aria-hidden="true"></i>
          </button>
        </div>
      `;
      return messageWrapper;
    };

  })(Drupal);