<?php

/**
 * @file
 * Contains tb_migrations.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function tb_migrations_aventri_sync() {
  /** @var \Drupal\wwf_shopify\ShopifySync $sync_manager */
  $sync_manager = \Drupal::service('tb_migrations.sync_aventri');
  $sync_manager->sync();
}

function tb_migrations_isearch_sync() {
  /** @var \Drupal\wwf_shopify\ShopifySync $sync_manager */
  $sync_manager = \Drupal::service('tb_migrations.sync_isearch');
  $sync_manager->sync();
}
